#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';


use App\Console\Commands\ParseCommand;
use Symfony\Component\Console\Application;

$application = new Application();

// ... register commands
$application->add(new ParseCommand());

$application->run();